immcantation:
  version:  2.3.0
  date:     2018.10.21
release:
  presto:   0.5.10
  changeo:  0.4.3
  alakazam: 0.2.11
  shazam:   0.1.10
  tigger:   0.3.1
  rdi:      1.0.0
  scoper:   0.1.0
  prestor:  0.0.5
software:
  muscle:   3.8.31
  cd-hit:   4.6.8
  vsearch:  2.8.4
  blast:    2.7.1
  igblast:  1.10.0
  phylip:   3.697
  igphyml:  1.0.5
  airr-py:  1.2.1
  airr-r:   1.2.0
