immcantation:
    version:  1.3.0
    date:     2017.10.17
release:
    presto:   0.5.4
    changeo:  0.3.9
    alakazam: 0.2.8
    shazam:   0.1.8
    tigger:   0.2.11
    prestor:  0.0.3
software:
    muscle:   3.8.31
    vsearch:  2.4.3
    blast:    2.5.0
    igblast:  1.7.0
    phylip:   3.696
