immcantation:
  version:  null
  date:     null
release:
  presto:   null
  changeo:  null
  alakazam: null
  shazam:   null
  tigger:   null
  rdi:      null
  prestor:  null
  scoper:   null
  igphyml:  null
software:
  muscle:   3.8.31
  cd-hit:   4.6.8
  vsearch:  2.8.4
  blast:    2.7.1
  igblast:  1.10.0
  phylip:   3.697
  airr-py:  1.2.1
  airr-r:   1.2.0